global using System.Text.Json.Serialization;
global using System.ComponentModel.DataAnnotations;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Microsoft.AspNetCore.Mvc;
global using SLAPI.Models;
global using static HelperMethods;
global using System.IO;
global using Serilog;
global using Serilog.Events;
global using Serilog.Extensions.Hosting;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore;
global using System.Net.Http.Headers;
